apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-watcher
spec:
  rules:
    -
      host: k8s-watcher
      http:
        paths:
          -
            backend:
              serviceName: k8s-watcher
              servicePort: 8080