apiVersion: v1
kind: Service
metadata:
  name: k8s-watcher
  labels:
    app: k8s-watcher
spec:
  clusterIP: None
  ports:
  - name: web
    port: 8080
  selector:
    app: k8s-watcher
  type: ClusterIP